name: Renovate

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest stable version

      - run: ls -l

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44
        with:
          # configurationFile: renovate/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_TFE_TOKEN: ${{ secrets.MY_TFE_TOKEN }}
          RENOVATE_CONFIG_FILE: renovate/renovate-config.js