name: Renovate

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: ls -l
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.0.1
        with:
          configurationFile: renovate/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_TFE_TOKEN: ${{ secrets.MY_TFE_TOKEN }}